/*
 * small_lib.c
 *
 * Collection of helper functions (seedRandom, is_numeric)
 * 
 *  Created on: Nov 27, 2009
 *      Author: Daniel+Maarten
 */
#include "MainProgram.h"

/* Method for seeding rand() from the /dev/urandom file */
void seedRandom(void) {
	FILE *urandom;
	unsigned int seed;

	//open the file '/dev/urandom' for reading
	//this file is a pool of random bytes generated by environmental noise
	//great for random number generating ^_^
	urandom = fopen("/dev/urandom", "r" );
	//read from it
	fread(&seed, sizeof(seed), 1 , urandom);
	//seed rand()
	srand(seed);
	//close file
	fclose(urandom);
}

/*Checks whether the given char array is numeric or not, returns 0 if not, 1 if it is*/
int is_numeric(const char *p) {
     if (*p) {
          char c;
          while ((c=*p++)) {
                if (!isdigit(c)) return 0;
          }
          return 1;
      }
      return 0;
}
